// Database types for Supabase
// This file would normally be generated by Supabase CLI
// For now, we'll define the types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'viewer' | 'editor' | 'admin' | 'super_admin'
export type RosterSessionType = 'initial_mel' | 'final_mel'
export type RosterSessionStatus = 'draft' | 'processing' | 'completed' | 'archived'
export type PromotionCycle = 'SRA' | 'SSG' | 'TSG' | 'MSG' | 'SMS' | 'CMS'
export type MemberCategory = 'eligible' | 'ineligible' | 'discrepancy' | 'btz' | 'small_unit'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          full_name: string | null
          rank: string | null
          grade: string | null
          unit: string | null
          role: UserRole
          avatar_url: string | null
          phone: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          full_name?: string | null
          rank?: string | null
          grade?: string | null
          unit?: string | null
          role?: UserRole
          avatar_url?: string | null
          phone?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          full_name?: string | null
          rank?: string | null
          grade?: string | null
          unit?: string | null
          role?: UserRole
          avatar_url?: string | null
          phone?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      units: {
        Row: {
          id: string
          name: string
          pascode: string
          parent_unit_id: string | null
          commander_id: string | null
          address: string | null
          phone: string | null
          email: string | null
          metadata: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          pascode: string
          parent_unit_id?: string | null
          commander_id?: string | null
          address?: string | null
          phone?: string | null
          email?: string | null
          metadata?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          pascode?: string
          parent_unit_id?: string | null
          commander_id?: string | null
          address?: string | null
          phone?: string | null
          email?: string | null
          metadata?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      unit_members: {
        Row: {
          id: string
          unit_id: string
          user_id: string
          role: UserRole
          assigned_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          user_id: string
          role?: UserRole
          assigned_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          user_id?: string
          role?: UserRole
          assigned_at?: string
        }
      }
      roster_sessions: {
        Row: {
          id: string
          session_type: RosterSessionType
          cycle: PromotionCycle
          year: number
          status: RosterSessionStatus
          created_by: string | null
          unit_id: string | null
          file_name: string | null
          file_path: string | null
          file_size: number | null
          total_members: number
          statistics: Json
          metadata: Json
          processing_started_at: string | null
          processing_completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          session_type: RosterSessionType
          cycle: PromotionCycle
          year: number
          status?: RosterSessionStatus
          created_by?: string | null
          unit_id?: string | null
          file_name?: string | null
          file_path?: string | null
          file_size?: number | null
          total_members?: number
          statistics?: Json
          metadata?: Json
          processing_started_at?: string | null
          processing_completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          session_type?: RosterSessionType
          cycle?: PromotionCycle
          year?: number
          status?: RosterSessionStatus
          created_by?: string | null
          unit_id?: string | null
          file_name?: string | null
          file_path?: string | null
          file_size?: number | null
          total_members?: number
          statistics?: Json
          metadata?: Json
          processing_started_at?: string | null
          processing_completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      roster_members: {
        Row: {
          id: string
          session_id: string
          ssan: string
          last_4_ssn: string | null
          full_name: string
          last_name: string | null
          first_name: string | null
          middle_initial: string | null
          rank: string | null
          grade: string | null
          afsc: string | null
          unit: string | null
          pascode: string | null
          date_of_rank: string | null
          dos: string | null
          dor: string | null
          pdd: string | null
          ets: string | null
          category: MemberCategory
          is_eligible: boolean
          eligibility_reason: string | null
          eligibility_data: Json
          is_btz_eligible: boolean
          btz_data: Json
          is_edited: boolean
          edit_history: Json[]
          original_data: Json | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          session_id: string
          ssan: string
          full_name: string
          last_name?: string | null
          first_name?: string | null
          middle_initial?: string | null
          rank?: string | null
          grade?: string | null
          afsc?: string | null
          unit?: string | null
          pascode?: string | null
          date_of_rank?: string | null
          dos?: string | null
          dor?: string | null
          pdd?: string | null
          ets?: string | null
          category?: MemberCategory
          is_eligible?: boolean
          eligibility_reason?: string | null
          eligibility_data?: Json
          is_btz_eligible?: boolean
          btz_data?: Json
          is_edited?: boolean
          edit_history?: Json[]
          original_data?: Json | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          ssan?: string
          full_name?: string
          last_name?: string | null
          first_name?: string | null
          middle_initial?: string | null
          rank?: string | null
          grade?: string | null
          afsc?: string | null
          unit?: string | null
          pascode?: string | null
          date_of_rank?: string | null
          dos?: string | null
          dor?: string | null
          pdd?: string | null
          ets?: string | null
          category?: MemberCategory
          is_eligible?: boolean
          eligibility_reason?: string | null
          eligibility_data?: Json
          is_btz_eligible?: boolean
          btz_data?: Json
          is_edited?: boolean
          edit_history?: Json[]
          original_data?: Json | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      senior_raters: {
        Row: {
          id: string
          session_id: string
          pascode: string
          name: string
          rank: string | null
          title: string | null
          signature_block: string | null
          email: string | null
          phone: string | null
          is_small_unit_rater: boolean
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          session_id: string
          pascode: string
          name: string
          rank?: string | null
          title?: string | null
          signature_block?: string | null
          email?: string | null
          phone?: string | null
          is_small_unit_rater?: boolean
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          pascode?: string
          name?: string
          rank?: string | null
          title?: string | null
          signature_block?: string | null
          email?: string | null
          phone?: string | null
          is_small_unit_rater?: boolean
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      reports: {
        Row: {
          id: string
          session_id: string
          report_type: string
          report_name: string | null
          file_path: string | null
          file_size: number | null
          format: string | null
          generation_params: Json
          metadata: Json
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          report_type: string
          report_name?: string | null
          file_path?: string | null
          file_size?: number | null
          format?: string | null
          generation_params?: Json
          metadata?: Json
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          report_type?: string
          report_name?: string | null
          file_path?: string | null
          file_size?: number | null
          format?: string | null
          generation_params?: Json
          metadata?: Json
          created_by?: string | null
          created_at?: string
        }
      }
      custom_logos: {
        Row: {
          id: string
          session_id: string | null
          unit_id: string | null
          file_name: string
          file_path: string
          file_size: number | null
          mime_type: string | null
          dimensions: Json | null
          uploaded_by: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          session_id?: string | null
          unit_id?: string | null
          file_name: string
          file_path: string
          file_size?: number | null
          mime_type?: string | null
          dimensions?: Json | null
          uploaded_by?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string | null
          unit_id?: string | null
          file_name?: string
          file_path?: string
          file_size?: number | null
          mime_type?: string | null
          dimensions?: Json | null
          uploaded_by?: string | null
          is_active?: boolean
          created_at?: string
        }
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          entity_type: string | null
          entity_id: string | null
          changes: Json | null
          metadata: Json
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          entity_type?: string | null
          entity_id?: string | null
          changes?: Json | null
          metadata?: Json
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          action?: string
          entity_type?: string | null
          entity_id?: string | null
          changes?: Json | null
          metadata?: Json
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
      }
    }
    Views: {}
    Functions: {
      calculate_roster_statistics: {
        Args: {
          session_id_param: string
        }
        Returns: Json
      }
    }
    Enums: {
      user_role: UserRole
      roster_session_type: RosterSessionType
      roster_session_status: RosterSessionStatus
      promotion_cycle: PromotionCycle
      member_category: MemberCategory
    }
  }
}